name: Changelog generator
description: Generates and publishes a changelog for the given release version
inputs:
  version:
    description: Version number
    required: true
  prev_version:
    description: Previous version number
    required: false
  token:
    description: GitHub token with read/write access to all necessary repositories
    required: true
  output_file:
    description: A file to store resulting changelog markdown
    required: false
outputs:
  changelog:
    description: Changelog contents between the two given versions in Markdown format
runs:
  using: 'node20'
  main: 'index.js'
  
