name: 'Report Coverage'
description: 'Processes and uploads coverage reports from Go tests'

inputs:
  unit-cov-path:
    description: 'Path to unit test coverage file'
    required: true
  integration-cov-path:
    description: 'Path to integration test coverage file'
    required: true
  codecov-token:
    description: 'Token for CodeCov'
    required: true

runs:
  using: "composite"
  steps:
    - name: Join coverage outputs
      shell: bash
      run: |
        cp ${{ inputs.unit-cov-path }} backend.cov
        tail -n+2 ${{ inputs.integration-cov-path }} >> backend.cov

    - name: Convert coverage info to per-func stats
      shell: bash
      run: go tool cover -func backend.cov > backend-funcs.log

    - name: Convert coverage info to HTML
      shell: bash
      run: go tool cover -html backend.cov -o backend.html

    - name: Upload coverage file
      uses: actions/upload-artifact@v4
      with:
        name: backend-cov
        path: |
          backend.cov
          backend-funcs.log
          backend.html
        retention-days: 30
        compression-level: 9

    - name: Set summary to total coverage
      shell: bash
      run: |
        echo '# Coverage' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        grep 'total:' backend-funcs.log | tr '\t' ' ' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Report coverage to CodeCov
      uses: codecov/codecov-action@v5
      with:
        files: backend.cov
        flags: unified-backend
        name: backend
        slug: grafana/grafana
        # This URL doesn't use the Google auth, but is much more locked down. As such, it requires OIDC or a CodeCov-provided token to do anything.
        url: https://codecov-webhook.grafana-dev.net
        token: ${{ inputs.codecov-token }}
